// audiomack-slug-overrides.ts
export const AUDIOMACK_ARTISTS: Array<{ slug: string; audiomackSlug: string }> =
  [
    // ── Nigeria ───────────────────────────────────────────────────────────────
    { slug: 'adekunle-gold', audiomackSlug: 'adekunlegold' },
    { slug: 'asake', audiomackSlug: 'asakemusic' },
    { slug: 'ayra-starr', audiomackSlug: 'ayrastarr' },
    { slug: 'bayanni', audiomackSlug: 'bayanni' },
    { slug: 'bella-shmurda', audiomackSlug: 'bella-shmurda' },
    { slug: 'blaqbonez', audiomackSlug: 'blaqbonez' },
    { slug: 'bnxn', audiomackSlug: 'bnxn' },
    { slug: 'boi-chase', audiomackSlug: 'boi-chase' },
    { slug: 'boy-muller', audiomackSlug: 'boymuller' },
    { slug: 'boy-spyce', audiomackSlug: 'boyspyce' },
    { slug: 'burna-boy', audiomackSlug: 'burna-boy' },
    { slug: 'chike', audiomackSlug: 'officialchike' },
    { slug: 'ckay', audiomackSlug: 'ckay_yo' },
    { slug: 'crayon', audiomackSlug: 'crayonthis' },
    { slug: 'cruel-santino', audiomackSlug: 'cruelsantino' },
    { slug: 'davido', audiomackSlug: 'davido' },
    { slug: 'dj-tunez', audiomackSlug: 'dj-tunez' },
    { slug: 'falz', audiomackSlug: 'falzthebahdguy' },
    { slug: 'famous-pluto', audiomackSlug: 'famousplutouzama' },
    { slug: 'fave', audiomackSlug: 'fave' },
    { slug: 'fido', audiomackSlug: 'mrfidooooo' },
    { slug: 'fireboy-dml', audiomackSlug: 'fireboydml' },
    { slug: 'flavour', audiomackSlug: 'flavour' },
    { slug: 'fola', audiomackSlug: 'folapondis' },
    { slug: 'jae5', audiomackSlug: 'jae5' },
    { slug: 'joeboy', audiomackSlug: 'joeboy' },
    { slug: 'johnny-drille', audiomackSlug: 'johnny-drille' },
    { slug: 'khaid', audiomackSlug: 'khaid' },
    { slug: 'kizz-daniel', audiomackSlug: 'kizzdaniel' },
    { slug: 'kvng-vinci', audiomackSlug: 'kvngvinci' },
    { slug: 'ladipoe', audiomackSlug: 'ladipoe' },
    { slug: 'larry-gaaga', audiomackSlug: 'larry-gaaga' },
    { slug: 'lojay', audiomackSlug: 'lojay' },
    { slug: 'magixx', audiomackSlug: 'magixx' },
    { slug: 'mercy-chinwo', audiomackSlug: 'mercychinwo' },
    { slug: 'minz', audiomackSlug: 'minznse' },
    { slug: 'mohbad', audiomackSlug: 'mohbad' },
    { slug: 'mr-eazi', audiomackSlug: 'mr-eazi' },
    { slug: 'muyeez', audiomackSlug: 'muyeez' },
    { slug: 'naira-marley', audiomackSlug: 'naira-marley' },
    { slug: 'ndotz', audiomackSlug: 'ndotz' },
    { slug: 'no11', audiomackSlug: 'no11' },
    { slug: 'odumodublvck', audiomackSlug: 'odumodublvck' },
    { slug: 'olamide', audiomackSlug: 'olamide' },
    { slug: 'olivetheboy', audiomackSlug: 'olivetheboy_' },
    { slug: 'omah-lay', audiomackSlug: 'omah-lay' },
    { slug: 'oxlade', audiomackSlug: 'oxladeofficial' },
    { slug: 'p-square', audiomackSlug: 'psquare' },
    { slug: 'patoranking', audiomackSlug: 'patorankingfire' },
    { slug: 'pheelz', audiomackSlug: 'pheelzmrproducer' },
    { slug: 'qing-madi', audiomackSlug: 'qingmadi' },
    { slug: 'rema', audiomackSlug: 'heisrema' },
    { slug: 'ruger', audiomackSlug: 'rugerofficial' },
    { slug: 'runtown', audiomackSlug: 'runtown' },
    { slug: 'sarz', audiomackSlug: 'only1sarz' },
    { slug: 'seyi-vibez', audiomackSlug: 'seyivibezmusic' },
    { slug: 'shallipopi', audiomackSlug: 'shallipopi' },
    { slug: 'shoday', audiomackSlug: 'officialshoday' },
    { slug: 'simi', audiomackSlug: 'simi' },
    { slug: 'spinall', audiomackSlug: 'spinall' },
    { slug: 'spyro', audiomackSlug: 'spyro' },
    { slug: 'tems', audiomackSlug: 'temsbaby' },
    { slug: 'tiwa-savage', audiomackSlug: 'tiwa-savage' },
    { slug: 'tuff-king', audiomackSlug: 'tuff-king' },
    { slug: 'txc', audiomackSlug: 'txc' },
    { slug: 'victony', audiomackSlug: 'victony' },
    { slug: 'wande-coal', audiomackSlug: 'wandecoal' },
    { slug: 'wizkid', audiomackSlug: 'wizkid' },
    { slug: 'yemi-alade', audiomackSlug: 'yemialade' },
    { slug: 'young-jonn', audiomackSlug: 'youngjonn' },
    { slug: 'zerrydl', audiomackSlug: 'iamzerry' },
    { slug: 'zinoleesky', audiomackSlug: 'zinoleesky' },
    { slug: 'zlatan', audiomackSlug: 'zlatan_ibile' },
    { slug: 'ayo-maff', audiomackSlug: 'ayomaff' },
    { slug: '1da-banton', audiomackSlug: '1dabanton' },
    { slug: '2baba', audiomackSlug: '2baba' },
    { slug: 'boj', audiomackSlug: 'boj' },
    { slug: 'bloody-civilian', audiomackSlug: 'bloodycivilian' },

    // ── Ghana ─────────────────────────────────────────────────────────────────
    { slug: 'amaarae', audiomackSlug: 'amaarae' },
    { slug: 'black-sherif', audiomackSlug: 'black-sherif' },
    { slug: 'camidoh', audiomackSlug: 'camidoh' },
    { slug: 'dopenation', audiomackSlug: 'ghdopenation' },
    { slug: 'gyakie', audiomackSlug: 'gyakie_' },
    { slug: 'kidi', audiomackSlug: 'kidi' },
    { slug: 'king-promise', audiomackSlug: 'kingpromise' },
    { slug: 'olivetheboy', audiomackSlug: 'olivetheboy_' },
    { slug: 'r2bees', audiomackSlug: 'r2bees' },
    { slug: 'sarkodie', audiomackSlug: 'sarkodie' },
    { slug: 'shatta-wale', audiomackSlug: 'shattawalenima' },

    // ── South Africa ──────────────────────────────────────────────────────────
    { slug: '031choppa', audiomackSlug: '031choppa' },
    { slug: 'big-zulu', audiomackSlug: 'bigzulu' },
    { slug: 'black-coffee', audiomackSlug: 'black-coffee' },
    { slug: 'blxckie', audiomackSlug: 'blxckie' },
    { slug: 'boohle', audiomackSlug: 'boohle' },
    { slug: 'cassper-nyovest', audiomackSlug: 'casspernyovest' },
    { slug: 'chcco', audiomackSlug: 'chcco' },
    { slug: 'die-antwoord', audiomackSlug: 'dieantwoord' },
    { slug: 'dj-lace', audiomackSlug: 'djlace' },
    { slug: 'dj-maphorisa', audiomackSlug: 'dj-maphorisa' },
    { slug: 'dj-zinhle', audiomackSlug: 'dj-zinhle' },
    { slug: 'dlala-thukzin', audiomackSlug: 'dlalathukzin' },
    { slug: 'elaine', audiomackSlug: 'elaineofficial' },
    { slug: 'focalistic', audiomackSlug: 'focalistic' },
    { slug: 'kabza-de-small', audiomackSlug: 'kabzadesmallmusic' },
    { slug: 'kelvin-momo', audiomackSlug: 'kelvinmomo' },
    { slug: 'lloyiso', audiomackSlug: 'lloyiso' },
    { slug: 'lucky-dube', audiomackSlug: 'lucky-dube' },
    { slug: 'major-league-djz', audiomackSlug: 'majorleaguedjz' },
    { slug: 'mawhoo', audiomackSlug: 'mawhoo' },
    { slug: 'mellow-and-sleazy', audiomackSlug: 'mellowsleazy' },
    { slug: 'mlindo-the-vocalist', audiomackSlug: 'mlindothevocalist' },
    { slug: 'myztro', audiomackSlug: 'myztro' },
    { slug: 'nasty-c', audiomackSlug: 'nasty-c' },
    { slug: 'nkosazana-daughter', audiomackSlug: 'nkosazanadaughter' },
    { slug: 'prince-kaybee', audiomackSlug: 'prince-kaybee-1' },
    { slug: 'royal-musiq', audiomackSlug: 'officialroyalmusiq' },
    { slug: 'sam-deep', audiomackSlug: 'realsamdeep' },
    { slug: 'shakes-and-les', audiomackSlug: 'shakesles' },
    { slug: 'shaunmusiq', audiomackSlug: 'shaunmusiq' },
    { slug: 'sjava', audiomackSlug: 'sjava' },
    { slug: 'sun-el-musician', audiomackSlug: 'sunelmusicianza' },
    { slug: 'tyla', audiomackSlug: 'tyla' },
    { slug: 'tyler-icu', audiomackSlug: 'tylericu' },
    { slug: 'uncle-waffles', audiomackSlug: 'unclewaffles' },
    { slug: 'xduppy', audiomackSlug: 'xduppy' },
    { slug: 'young-stunna', audiomackSlug: 'youngstunna' },
    { slug: 'zee-nxumalo', audiomackSlug: 'zee-nxumalo' },

    // ── Tanzania ──────────────────────────────────────────────────────────────
    { slug: 'diamond-platnumz', audiomackSlug: 'diamondplatnumz' },
    { slug: 'harmonize', audiomackSlug: 'harmonize' },
    { slug: 'rayvanny', audiomackSlug: 'rayvanny' },

    // ── Kenya ─────────────────────────────────────────────────────────────────
    { slug: 'bien', audiomackSlug: 'bien' },
    { slug: 'idd-aziz', audiomackSlug: 'idd-aziz' },
    { slug: 'sauti-sol', audiomackSlug: 'sautisol' },
    { slug: 'sofiya-nzau', audiomackSlug: 'sofiyanzau' },
    { slug: 'joshua-baraka', audiomackSlug: 'joshuabaraka' },

    // ── Uganda ────────────────────────────────────────────────────────────────
    { slug: 'kapa-boy', audiomackSlug: 'kapa-boy-1' },

    // ── Côte d'Ivoire ─────────────────────────────────────────────────────────
    { slug: 'alpha-blondy', audiomackSlug: 'alphablondy' },
    { slug: 'didi-b', audiomackSlug: 'didib' },
    { slug: 'fally-ipupa', audiomackSlug: 'fally-ipupa' },
    { slug: 'magic-system', audiomackSlug: 'magicsystem' },
    { slug: 'tiken-jah-fakoly', audiomackSlug: 'tikenjahfakoly' },

    // ── Cameroon ──────────────────────────────────────────────────────────────
    { slug: 'tayc', audiomackSlug: 'tayc' },

    // ── Senegal ───────────────────────────────────────────────────────────────
    { slug: 'akon', audiomackSlug: 'akon' },

    // ── Zambia ────────────────────────────────────────────────────────────────
    { slug: 'the-second-voice', audiomackSlug: 'the-second-voice' },

    // ── Mixed / Unknown origin ────────────────────────────────────────────────
    { slug: 'ciza', audiomackSlug: 'ciza' },
    { slug: 'deobi', audiomackSlug: 'Deobi' },
    { slug: 'evado', audiomackSlug: 'evadolee' },
    { slug: 'jnr-elder', audiomackSlug: 'jnr-elder' },
    { slug: 'mavo', audiomackSlug: 'mavo1' },
    { slug: 'muyeez', audiomackSlug: 'muyeez' },
    { slug: 'no11', audiomackSlug: 'no11' },
    { slug: 'tuff-king', audiomackSlug: 'tuff-king' },
    { slug: 'txc', audiomackSlug: 'txc' },
  ];
